### ISSUE TITLE
Can "labels" also be continuous variables?

### ISSUE THREAD

**Issue by dominik-rehse** [aangelopoulos/ppi_py#10]
Thanks for this awesome package. As far as I could read them, both the package docs as well as the related research papers mostly speak of "labels" for X and Y. However, some of the examples also use continuous variables. Will this package work also for continous variables for both X, Y, Yhat, X_unlabeled etc.?

**Comment by aangelopoulos** [comment]
Hey Dominik! Nice to meet you! And thanks :)

X and X_unlabeled can be continuous in any example.

Y can be continuous in any example except for logistic regression, and Yhat can always be continuous.

Does this help? Thanks!

**Comment by dominik-rehse** [comment]
Excellent, thanks!
